language: node_js
node_js:
- '8'

cache:
  directories:
    - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: bayyuaji/sample-react-apps
  bucket: sepulsacodedeploy
  region: ap-southeast-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: sepulsacodedeploy
  key: react-v4.zip
  bundle_type: zip
  application: SampleReactApps
  deployment_group: ReactJS
  region: ap-southeast-1
  on: *2

script:
  - yarn build
  - zip -r react-v4 *
  - mkdir -p dpl_cd_upload
  - mv react-v4.zip dpl_cd_upload/react-v4.zip
